CREATE TABLE IF NOT EXISTS Letter (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sender VARCHAR(50) NOT NULL,
    recipient VARCHAR(50) NOT NULL,
    message VARCHAR(500) NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);